@startuml
'https://plantuml.com/class-diagram

Class HomePage{
main()
start()
}

Class HomePageController{

listDisplay : TestField
addListClicked()
removeListClicked()
 editListClicked()
}

JavaFx.Application <|-- HomePage

HomePage--HomePageController
@enduml